### ISSUE TITLE
[SearchLight] - Can't edit primary key before saving

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieFrameworkDemos_NewAPI#1]
In the [Database app](https://github.com/GenieFramework/GenieFrameworkDemos_NewAPI/tree/main/Database), I have two objects and tables: Houses and Prediction. Every time I input a new House id in the text field, a new Prediction is created and added to the Predictions table.

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/5058397/211361565-bffdf868-e1e0-4687-9a22-8e4183ef4f4a.png">

I'm trying to set the id of the prediction to the id of the house. However, when I set this value either as an Int or  as a DbId type 

https://github.com/GenieFramework/GenieFrameworkDemos_NewAPI/blob/7ef71f629026736c1df3406005dd826e69e17002/Database/app.jl#L25-L31

I'm getting an error:

```julia
[ Info: 2023-01-09 17:35:08 SELECT "houses"."id" AS "houses_id", "houses"."CRIM" AS "houses_CRIM", "houses"."ZN" AS "houses_ZN", "houses"."INDUS" AS "houses_INDUS", "houses"."CHAS" AS "houses_CHAS", "houses"."NOX" AS "houses_NOX", "houses"."RM" AS "houses_RM", "houses"."AGE" AS "houses_AGE", "houses"."DIS" AS "houses_DIS", "houses"."RAD" AS "houses_RAD", "houses"."TAX" AS "houses_TAX", "houses"."PTRATIO" AS "houses_PTRATIO", "houses"."B" AS "houses_B", "houses"."LSTAT" AS "houses_LSTAT", "houses"."MEDV" AS "houses_MEDV" FROM "houses" WHERE id == 15 ORDER BY houses.id ASC
__model__.prediction[] = Prediction
| KEY               | VALUE                   |
|-------------------|-------------------------|
| error::Float64    | 0.14353387768486314     |
| id::DbId          | 15                      |
| price::Float64    | 18.056466122315136      |
| timestamp::String | 2023-01-09T17:35:08.773 |

[ Info: 2023-01-09 17:35:08 UPDATE predictions SET  "id" = '15', "price" = 18.056466122315136, "error" = 0.14353387768486314, "timestamp" = '2023-01-09T17:35:08.773' WHERE predictions.id = '15' ; SELECT 15 AS LAST_INSERT_ID
[ Info: 2023-01-09 17:35:08 SELECT "predictions"."id" AS "predictions_id", "predictions"."price" AS "predictions_price", "predictions"."error" AS "predictions_error", "predictions"."timestamp" AS "predictions_timestamp" FROM "predictions" WHERE "id" = 15 ORDER BY predictions.id ASC
┌ Error: 2023-01-09 17:35:08 Error attempting to invoke handler 3 for field Reactive{Int64}(Observable{Int64} with 3 listeners. Value:
│ 15, 1, false, false, "/Users/pere/genie/demos/GenieFrameworkDemos_NewAPI/Database/app.jl:19") with value 15
└ @ Stipple ~/.julia/packages/Stipple/AUtza/src/stipple/mutators.jl:33
┌ Error: 2023-01-09 17:35:08 SearchLight.Exceptions.UnretrievedModelException{DataType}(Prediction, 15, "UnretrievedModelException: the DataType data could not be retrieved for id 15. \nModel: \nPrediction")
└ @ Stipple ~/.julia/packages/Stipple/AUtza/src/stipple/mutators.jl:34
```

If I comment out that line it works, but the id assigned to the prediction is incremental. I could add a new column with the House id, but I wonder if it is possible to have the tables House and Predictions share their primary keys (some kind of relational key?)

**Comment by essenciary** [comment]
@PGimenez 
You could use this kind of convention where you use the same id for both but it's a bad idea, for multiple reasons: 

a) it does not work in real life, with concurrent access (multiple users). When you have multiple users adding rows, the insert operations will run out of sync, becoming very difficult to "reserve" ids.

b) in terms of database design, it's not a good approach - by using foreign keys you can define relationships at database level to trigger cascade deletes and other operations.

c) same goes for what the users expect - most people will understand that there is a relationship by looking at the foreign keys. 

d) SearchLight maps to the concept of primary key <-> foreign key with the Relationships API, allowing to set and manage relationships.

As such, we'd be showcasing a non-standard and not good approach to DB design, which is not ideal for a tutorial. Best thing would be to use the SearchLight Relationship API (which is not extensively documented though).

**Comment by essenciary** [comment]
But if you run a quick initial iteration using this approach, it won't work through the ORM. You'll need to run a query, something like: 

```julia
prediction.price = model([getfield(house, i) for i in 2:14])[1]
prediction.error = abs(prediction.price - house.MEDV)
prediction.timestamp = string(now())
@show prediction
save!(prediction)

SearchLight.query("
UPDATE predictions set id = $(house.id) where id = $(prediction.id)
")

# then retrieve prediction using the new id, if neede
prediction = findone(Prediction, id = house.id)
```
